version: '3'
services:
    web:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./docker/nginx.conf:/etc/nginx/conf.d/nginx.conf
        - ./app:/app:z
    php:
      build:
        args:
          user: user
          uid: 1000
        context: .
        dockerfile: ./docker/php/PHP.Dockerfile
      volumes:
        - ./app:/app
    mysql:
      image: mysql:5.7
      container_name: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: '1'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: '1'
        MYSQL_DATABASE: 'laravel'
      volumes:
        - ./docker/mysqldata:/var/lib/mysql:z
      ports:
        - 3306:3306
